<a href="https://colab.research.google.com/github/AdepuTejaswini9/B21_1423/blob/main/LAB_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
test_scores = np.random.randint(50, 101, size=(4, 4))
print(test_scores)

[[88 64 68 83]
 [80 96 90 97]
 [66 95 98 81]
 [81 81 66 90]]


In [4]:
column_means = np.mean(test_scores, axis=0)
row_means = np.mean(test_scores, axis=1)

print("Column-wise means:", column_means)
print("Row-wise means:", row_means)

Column-wise means: [78.75 84.   80.5  87.75]
Row-wise means: [75.75 90.75 85.   79.5 ]


In [5]:
std_dev = np.std(test_scores)
variance = np.var(test_scores)

print("Standard Deviation:", std_dev)
print("Variance:", variance)

Standard Deviation: 11.294356998076518
Variance: 127.5625


In [6]:
min_value = np.min(test_scores)
max_value = np.max(test_scores)
min_index = np.argmin(test_scores)
max_index = np.argmax(test_scores)

print("Minimum value:", min_value)
print("Maximum value:", max_value)
print("Index of minimum value:", min_index)
print("Index of maximum value:", max_index)

Minimum value: 64
Maximum value: 98
Index of minimum value: 1
Index of maximum value: 10


In [7]:
print("Statistical Analysis Summary:")
print(f"Row-wise means: {row_means}")
print(f"Column-wise means: {column_means}")
print(f"Overall Standard Deviation: {std_dev}")
print(f"Overall Variance: {variance}")
print(f"Global Minimum Value: {min_value} (Index: {min_index})")
print(f"Global Maximum Value: {max_value} (Index: {max_index})")

Statistical Analysis Summary:
Row-wise means: [75.75 90.75 85.   79.5 ]
Column-wise means: [78.75 84.   80.5  87.75]
Overall Standard Deviation: 11.294356998076518
Overall Variance: 127.5625
Global Minimum Value: 64 (Index: 1)
Global Maximum Value: 98 (Index: 10)


In [8]:
rgb_image = np.random.randint(0, 256, size=(3, 3, 3))
print(rgb_image)

[[[124   3  27]
  [  8  90 175]
  [120 117  61]]

 [[167  98  26]
  [213  71 134]
  [197  71  92]]

 [[121 193  35]
  [150 196 171]
  [ 89 103 176]]]


In [9]:
red_channel = rgb_image[:, :, 0]
green_channel = rgb_image[:, :, 1]
blue_channel = rgb_image[:, :, 2]
print("Red Channel:\n", red_channel)
print("Green Channel:\n", green_channel)
print("Blue Channel:\n", blue_channel)

Red Channel:
 [[124   8 120]
 [167 213 197]
 [121 150  89]]
Green Channel:
 [[  3  90 117]
 [ 98  71  71]
 [193 196 103]]
Blue Channel:
 [[ 27 175  61]
 [ 26 134  92]
 [ 35 171 176]]


In [10]:
red_mean = np.mean(red_channel)
green_mean = np.mean(green_channel)
blue_mean = np.mean(blue_channel)
print(f"Average pixel intensity for Red channel: {red_mean}")
print(f"Average pixel intensity for Green channel: {green_mean}")
print(f"Average pixel intensity for Blue channel: {blue_mean}")

Average pixel intensity for Red channel: 132.11111111111111
Average pixel intensity for Green channel: 104.66666666666667
Average pixel intensity for Blue channel: 99.66666666666667


In [11]:
brightness_increase = 50
brightened_image = np.clip(rgb_image + brightness_increase, 0, 255)
print("Brightened Image (clipped at 255):\n", brightened_image)

Brightened Image (clipped at 255):
 [[[174  53  77]
  [ 58 140 225]
  [170 167 111]]

 [[217 148  76]
  [255 121 184]
  [247 121 142]]

 [[171 243  85]
  [200 246 221]
  [139 153 226]]]


In [12]:
print("Statistical Analysis Summary:")
print("Red Channel:\n", red_channel)
print("Green Channel:\n", green_channel)
print("Blue Channel:\n", blue_channel)
print(f"\nAverage pixel intensity for Red channel: {red_mean}")
print(f"Average pixel intensity for Green channel: {green_mean}")
print(f"Average pixel intensity for Blue channel: {blue_mean}")
print("\nBrightened Image (clipped at 255):\n", brightened_image)

Statistical Analysis Summary:
Red Channel:
 [[124   8 120]
 [167 213 197]
 [121 150  89]]
Green Channel:
 [[  3  90 117]
 [ 98  71  71]
 [193 196 103]]
Blue Channel:
 [[ 27 175  61]
 [ 26 134  92]
 [ 35 171 176]]

Average pixel intensity for Red channel: 132.11111111111111
Average pixel intensity for Green channel: 104.66666666666667
Average pixel intensity for Blue channel: 99.66666666666667

Brightened Image (clipped at 255):
 [[[174  53  77]
  [ 58 140 225]
  [170 167 111]]

 [[217 148  76]
  [255 121 184]
  [247 121 142]]

 [[171 243  85]
  [200 246 221]
  [139 153 226]]]
